package ru.yandex.server.handlers.model;

public enum Endpoint {
    ADD_UPDATE_TASK,
    ADD_UPDATE_EPIC,
    ADD_UPDATE_SUBTASK,
    GET_TASK,
    GET_EPIC,
    GET_SUBTASK,
    DELETE_TASK,
    DELETE_EPIC,
    DELETE_SUBTASK,
    GET_ALL_TASKS,
    GET_ALL_EPICS,
    GET_ALL_SUBTASKS,
    GET_ALL_EPIC_SUBTASKS,
    DELETE_ALL_TASKS,
    DELETE_ALL_EPICS,
    DELETE_ALL_SUBTASKS,
    UNKNOWN
}
